import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeHighlight from "rehype-highlight";
import { generateArticle } from "@/services/geminiService";
import { cacheService } from "@/services/cacheService";
import { Loader2, AlertCircle, Clock, Tag } from "lucide-react";

export function Article() {
  const { category, topic } = useParams<{ category: string; topic: string }>();
  const [content, setContent] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  const displayTopic = topic?.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ') || "Unknown Topic";
  const displayCategory = category?.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ') || "General";

  useEffect(() => {
    if (!category || !topic) return;

    let isMounted = true;
    const cacheKey = `${category}_${topic}`;

    const fetchContent = async () => {
      setLoading(true);
      setError(null);

      // Check cache first
      const cached = cacheService.get(cacheKey);
      if (cached) {
        if (isMounted) {
          setContent(cached);
          setLoading(false);
        }
        return;
      }

      // Generate via AI
      try {
        const generated = await generateArticle(displayCategory, displayTopic);
        if (isMounted) {
          setContent(generated);
          cacheService.set(cacheKey, generated);
          setLoading(false);
        }
      } catch (err) {
        if (isMounted) {
          setError(err instanceof Error ? err.message : "An error occurred");
          setLoading(false);
        }
      }
    };

    fetchContent();

    return () => {
      isMounted = false;
    };
  }, [category, topic, displayCategory, displayTopic]);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[50vh] space-y-4 text-zinc-500">
        <Loader2 className="w-10 h-10 animate-spin text-indigo-600" />
        <p className="text-lg font-medium animate-pulse">Generating comprehensive article for "{displayTopic}"...</p>
        <p className="text-sm">This may take a few seconds as we compile history, concepts, and code examples.</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-red-50 border border-red-200 rounded-xl p-6 flex items-start gap-4 text-red-800">
        <AlertCircle className="w-6 h-6 shrink-0 mt-0.5" />
        <div>
          <h3 className="font-semibold text-lg mb-1">Failed to load article</h3>
          <p>{error}</p>
        </div>
      </div>
    );
  }

  return (
    <article className="animate-in fade-in duration-500">
      <header className="mb-8 pb-8 border-b border-zinc-200">
        <div className="flex items-center gap-4 text-sm text-zinc-500 mb-4">
          <span className="flex items-center gap-1.5 bg-zinc-100 px-2.5 py-1 rounded-md">
            <Tag className="w-4 h-4" />
            {displayCategory}
          </span>
          <span className="flex items-center gap-1.5">
            <Clock className="w-4 h-4" />
            Generated just now
          </span>
        </div>
        <h1 className="text-4xl md:text-5xl font-serif font-bold text-zinc-900 tracking-tight mb-4">
          {displayTopic}
        </h1>
        <p className="text-lg text-zinc-600 italic">
          From TechWiki, the free AI-generated tech encyclopedia.
        </p>
      </header>

      <div className="prose prose-zinc prose-lg max-w-none prose-headings:font-serif prose-headings:font-bold prose-a:text-indigo-600 hover:prose-a:text-indigo-800 prose-pre:bg-[#0d1117] prose-pre:border prose-pre:border-zinc-800 prose-code:text-indigo-600 prose-code:bg-indigo-50 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded-md prose-code:before:content-none prose-code:after:content-none">
        <ReactMarkdown
          remarkPlugins={[remarkGfm]}
          rehypePlugins={[rehypeHighlight]}
          components={{
            a: ({ node, ...props }) => {
              // Intercept internal links if they look like Wikipedia links
              const href = props.href || "";
              if (href.startsWith("/wiki/")) {
                return <Link to={href} {...props} />;
              }
              return <a target="_blank" rel="noopener noreferrer" {...props} />;
            }
          }}
        >
          {content}
        </ReactMarkdown>
      </div>
      
      <footer className="mt-16 pt-8 border-t border-zinc-200 text-sm text-zinc-500 text-center">
        <p>This article was generated by AI and cached locally for your convenience.</p>
      </footer>
    </article>
  );
}
